### ISSUE TITLE
Support for Outbox pattern

### ISSUE THREAD

**Issue by mayankst** [Farfetch/kafka-flow#137]
Hi,

Is implementation of outbox pattern on roadmap? With any large distributed app it is almost essential to have that, so would love to see it implemented for this library as well. 

Thanks

**Comment by dougolima** [comment]
Hi @mayankst,

The Outbox Pattern implementation is not in our roadmap because this pattern involves other resources (web api and database, for example) in addition to Kafka. Kafka-flow aims to facilitate both the consumption and the production of messages using Kafka, so it could be used in the intermediate component of this pattern (producing the messages that arrive in the outbox) and, also, facilitating the consumption of messages from this component.

Please let me know if you have any other questions.

Regards,
