### ISSUE TITLE
SerializationContext always empty in ConfluentSerializerWrapper 

### ISSUE THREAD

**Issue by schepersk** [Farfetch/kafka-flow#198]
KafkaFlow.SchemaRegistry.ConfluentSerializerWrapper is always providing an Empty instance of Confluent.Kafka.SerializationContext to the IAsyncySerializer instance.
Not providing the Topic name, always results in an unknown generated subject name "-value".

**Comment by dougolima** [comment]
Hi @schepersk, an empty SerializationContext doesn't use to be a problem with Schema Registry serializers.

 Can you please share your consumer configuration in order to try to reproduce this problem?

**Comment by schepersk** [comment]
Hi @dougolima, the problem is not on the consumer side, but on the producer side.

In the class KafkaFlow.SchemaRegistry.ConfluentSerializerWrapper, method SerializeAsync, a Confluent.Kafka.SerializationContext.Empty instance is always provided to the underlying IAsyncSerializer<T>. For that reason, a valid subject name cannot be generated.

**Comment by dougolima** [comment]
Hi @schepersk, when I said consumer configuration I meant producer configuration, sorry.

This error uses to happens when you try to publish different message types to the same topic using `SubjectNameStrategy.Topic`.

Empty SerializationContext has never given us any problem, so far.

Can you please share your **producer** configuration and more details like:
- AvroSerializerConfig
- KafkaFlow version
- Kafka version 
?
